version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: symfony/cache
    versions:
    - 5.2.2
    - 5.2.4
  - dependency-name: symfony/lock
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
